version: "2"

networks:
  flask:
    external: false

services:
  server:
    image: python-flask:latest
    # environment:
    #   - USER_UID=1000
    #   - USER_GID=1000
    restart: always
    networks:
      - flask
    # volumes:
    #   - ./gitea:/data
    ports:
      - "5000:5000"
    #   - "222:22"
