# goal: run simple python flask server
#
# steps:
# - [x] simple hello world
# - [ ] python stack
# - [ ] flask dev server
# - [ ] prod uwsgi or similar server

# questions:
# - hub has many results for python


FROM alpine:3.8

COPY hello.sh /hello.sh

CMD ["/hello.sh"]
